name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python_version: ["3.9", "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - name: Run tests
        run: poetry run python -m unittest
  format-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Black
        run: pip install black
      - name: Check black
        run: black --check poked tests
