name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install dependencies
        run: |
          poetry export -f requirements.txt --without-hashes --with dev --output requirements.txt
          pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Black
        run: pip install black
      - name: Check black
        run: black --check poked
